trigger:
  - main

pool:
  name: Default

variables:
  dockerHubUsername: 'chisomjude'
  imageName: 'JumiaDemoApp'

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildAndTest
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: pip install -r requirements.txt
            displayName: 'Install dependencies'
          - script: python -m pytest
            displayName: 'Run unit tests'

  - stage: PushImage
    displayName: 'Build & Push to Docker Hub'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DockerBuildPush
        steps:
          - task: Docker@2
            displayName: 'Build and push image'
            inputs:
              containerRegistry: 'dockerhub-connection'
              repository: '$(dockerHubUsername)/$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)